// PRODUCTS ACTIONS

export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'
export const FETCH_SINGLE_PRODUCT_ERROR = 'FETCH_SINGLE_PRODUCT_ERROR'

// AUTH

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'


// CART 

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const INCREASE_QUANITY = 'INCREASE_QUANTITIY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const SELECTED_PRODUCTS = 'SELECTED_PRODUCTS'
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT'

// ORDER 


export const PLACE_ORDER = 'PLACE_ORDER'
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR'