// PRODUCTS

export const FETCH_ALL_PROUDCTS = 'FETCH_ALL_PRODUCTS'
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR'

// CART


export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
